### ISSUE TITLE
readme issues

### ISSUE THREAD

**Issue by blinky3713** [f-o-a-m/chanterelle#3]

**Comment by bgoblirsch** [comment]
## Parking DAO
The Parking DAO is **a ~~a~~** set of smart contracts that encapsulate a User, 

## Build/Deploy Overview 
This repo is meant to be a templated complement to truffle. You can clone it and use it for development, deployment and testing of solidity smart contracts. It uses truffle as a build tool, taking advantage of **~~it's~~ its** bundled compiler.

### Build
In order to build the project, including all of the purescript files generated by purescript-web3-generator for each abi **"in"** the artifacts folder build/contracts, run

This will compile all new contracts including any existing contracts which have changed. It will also regenerate their corresponding purescript files, which means **~~you~~ it** will give you the benefit of type-errors when you have broken your existing application. Note that the solidity code will still compile, even if the purescript code doesn't.

### Deploy
You should see the logs from the deployment printed to the console, and the address for the recently deployed contract should be written to the corresponding build artifact's "networks" object under the key corresponding to the **~~networkId~~ network Id** of the network you were using. I.e., it follows truffle's existing pattern.
